# # 設定 nginx 健康檢查路由
# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: nginx-config
# data:
#   default.conf: |
#     server {
#       listen 80;
#       location / {
#         root /usr/share/nginx/html;
#         index index.html;
#       }
#       location /healthz {
#         return 200 'ok';
#         add_header Content-Type text/plain;
#       }
#     }

---
# deployment 管理 pod
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: coconut820/nginx-probe:latest
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /healthz
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
