apiVersion: external-secrets.io/v1
kind: SecretStore # 定義如何連接外部 secret 提供者 (這裡是 aws secrets manager)
metadata:
  name: aws-secret-store
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-east-2
      auth:
        secretRef: # 驗證方式: 從 k8s secrets 取得 aws 存取鑰匙
          accessKeyIDSecretRef:
            name: awssm-secret
            key: access-key
          secretAccessKeySecretRef:
            name: awssm-secret
            key: secret-access-key
