apiVersion: external-secrets.io/v1
kind: ExternalSecret # 這個是用於連接外部的 secret（這邊我用的是 Vault）
metadata:
  name: vault-external-secret
spec:
  refreshInterval: 1h
  secretStoreRef: # 指定要用哪個 SecretStore 來連接 Vault
    name: vault-secret-store
    kind: SecretStore
  target:
    name: vault-k8s-secrets # ESO 同步完成後，在 K8s 裡自動建立的 Secret 名稱
    creationPolicy: Owner
  data:
    - secretKey: vault-k8s-secrets # 寫入 K8s Secret 的 key 名稱
      remoteRef:
        # vault kv 中的dataset 名稱
        key: userdata # Vault 上的 secret path
