apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault-secret-store
spec:
  provider:
    vault:
      server: "http://vault.default.svc.cluster.local:8200" # ← 改成 K8s 內部 DNS
      path: "kv" # kv Engine
      auth:
        tokenSecretRef:
          name: "vault-root-auth"
          key: "token"

---
apiVersion: v1
kind: Secret
metadata:
  name: vault-root-auth
data:
  # 此為 echo -n '你的root-token' | base64
  token: <BASE64_ENCODED_VAULT_ROOT_TOKEN>
