apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: task6-crd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: ssh://git@43.212.192.6:2424/root/tes-helm.git
    targetRevision: HEAD
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
