apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: vault-config
spec:
  provider: vault
  parameters:
    vaultAddress: "http://vault.onpremiseadvisor.com" # Vault 服務的地址 
    roleName: "nginx-role" # Vault 中的 Role Name
    objects: |
      - objectName: "default.conf"
        secretPath: "secret/data/nginx/default.conf"
        secretKey: "config"
      - objectName: "redis.conf"
        secretPath: "secret/data/redis/redis.conf"
        secretKey: "config"