apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault-secret-store
spec:
  provider:
    vault:
      server: "http://vault-helm.vault-helm.svc.cluster.local:8200" # ← 改成 K8s 內部 DNS
      path: "secret" # kv Engine
      auth:
        tokenSecretRef:
          name: "vault-root-auth"
          key: "token"

---
apiVersion: v1
kind: Secret
metadata:
  name: vault-root-auth
data:
  # echo -n <root-token> | base64
  token: cm9vdA== # root