apiVersion: external-secrets.io/v1
kind: ExternalSecret # 這個是用於連接外部的 secret（這邊我用的是 Vault）
metadata:
  name: vault-external-secret
  namespace: task12
spec:
  refreshInterval: 1h
  secretStoreRef: # 指定要用哪個 SecretStore 來連接 Vault
    name: vault-secret-store
    kind: SecretStore
  target:
    name: vault-k8s-secrets # ESO 同步完成後，在 K8s 裡自動建立的 Secret 名稱
    creationPolicy: Owner
  data:    
    - secretKey: REDIS_HOST # 寫入 K8s Secret 的 key 名稱
      remoteRef:
        key: redis/userdata # 去 Vault 這個 path找資料
        property: REDIS_HOST # 拿這個 key 的值
    - secretKey: REDIS_PASSWORD
      remoteRef:
        key: redis/userdata
        property: REDIS_PASSWORD
    - secretKey: REDIS_PORT
      remoteRef:
        key: redis/userdata
        property: REDIS_PORT
    - secretKey: REDIS_USER
      remoteRef:
        key: redis/userdata
        property: REDIS_USER